name: save_smart_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.69.0
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
