name: save_smart_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.69.0
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  firebase_core: ^3.15.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0
  firebase_remote_config: ^5.3.0
  firebase_performance: ^0.10.1+3
  in_app_purchase: ^3.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/SaveSmart_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/SaveSmart_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
